name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
      
    - name: Deploy to web server
      uses: easingthemes/ssh-deploy@main
      with:
        SCRIPT_BEFORE: ls
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_USER: ${{ secrets.SSH_REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.SSH_REMOTE_HOST }}
        TARGET: ${{ secrets.SSH_TARGET }}
